[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sbibm"
description = "Simulation-based inference benchmark"
readme = "README.md"
dynamic = ["version"]
authors = [
    { name = "Jan-Matthis Lueckmann", email = "mail@jan-matthis.de" },
    { name = "Jan Boelts", email = "jan.boelts@mailbox.org" }
]
requires-python = ">=3.9"
license = { text = "MIT" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "autograd",
    "deneb",
    "diffeqtorch",
    "future",
    "joblib",
    "numpy>=1.26.4",
    "matplotlib",
    "pandas>=1.0.0",
    "sbi>=0.23.0",
    "pyro-ppl",
    "scikit-learn",
    "torch>=1.8.0",
    "tqdm",
]

[project.optional-dependencies]
dev = [
    # Lint
    "pre-commit == 4.0.1",
    "pyyaml",
    "pyright",
    "ruff==0.9.0",
    # Test
    "ipdb",
    "pytest",
    "pytest-plt",
    "pytest-xdist",
    "typeguard",
]

[project.urls]
documentation = "https://sbi-benchmark.github.io/"
source = "https://github.com/sbi-benchmark/sbibm"
tracker = "https://github.com/sbi-benchmark/sbibm/issues"

[tool.setuptools.packages.find]
include = ["sbibm*"]
exclude = ["tests", "tests.*", "sbibm/third_party"]

[tool.setuptools.dynamic]
version = {attr = "sbibm.__version__.__version__"}

# ruff configs
[tool.ruff]
extend-include = ["*.ipynb"]
line-length = 88

[tool.ruff.lint]
# pycodestyle, Pyflakes, pyupgrade, flake8-bugbear, flake8-simplify, isort
select = ["E", "F", "W", "B", "I"]
ignore = [
    "E731",  # allow naming lambda functions.
    "B008",  # allow function calls in default args.
    "E722",  # allow bare except.
    "E721",  # allow == for type comparison.
]

[tool.ruff.lint.extend-per-file-ignores]
"__init__.py" = ["E402", "F401", "F403"]  # allow unused imports and undefined names
"test_*.py" = ["F403", "F405"]
"tutorials/*.ipynb" = ["E501"]  # allow long lines in notebooks
"sbibm/third_party/*" = ["E402", "E501", "F811", "E741", "B904"]

[tool.ruff.lint.isort]
case-sensitive = true
lines-between-types = 0  # like isort default.
relative-imports-order = "furthest-to-closest"  # like isort default.
known-first-party = ["sbibm", "tests"]

[tool.ruff.format]
exclude = ["*.ipynb"]
preview = true
quote-style = "preserve"

# Pytest configuration
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning"
]
testpaths = ["tests"]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
xfail_strict = true
